/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.profile;

import controller.datarecords.Data;
import controller.helper.Helper;
import controller.helper.OutfitOperations;
import model.clothes.*;
import model.user.Gender;
import model.user.User;

import javax.swing.*;
import java.util.Objects;

/**
 *
 * @author tamer
 */
public class AddOutfit extends javax.swing.JFrame {
    private User user;
    private String item;
    public AddOutfit(User user,String item) {
        this.user = user;
        this.item = item;
        initComponents(user,item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(User user, String item) {

        outfitName = new javax.swing.JLabel();
        clothingType = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        clothingTypeList = new JComboBox<ClothingType>();
        genderList = new JComboBox<Gender>();
        sizeList = new JComboBox<Size>();
        colorList = new javax.swing.JComboBox<Color>();
        outfitNameInput = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        brandName = new javax.swing.JLabel();
        brandInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outfitName.setText("Outfit Name");

        clothingType.setText("Clothing Type");

        gender.setText("Gender");

        size.setText("Size");

        color.setText("Color");

        clothingTypeList.setModel(new javax.swing.DefaultComboBoxModel<ClothingType>(ClothingType.class.getEnumConstants()));

        genderList.setModel(new javax.swing.DefaultComboBoxModel<Gender>(Gender.class.getEnumConstants()));

        sizeList.setModel(new javax.swing.DefaultComboBoxModel<Size>(Size.class.getEnumConstants()));

        colorList.setModel(new javax.swing.DefaultComboBoxModel<Color>(Color.class.getEnumConstants()));

        outfitNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outfitNameInputActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        brandName.setText("Brand Name");

        brandInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clothingType)
                    .addComponent(gender)
                    .addComponent(size)
                    .addComponent(color)
                    .addComponent(brandName)
                    .addComponent(outfitName))
                .addGap(60, 287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outfitNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorList, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderList, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothingTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeList, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outfitName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outfitNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothingTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothingType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeList, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(submitButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outfitNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outfitNameInputActionPerformed
    }//GEN-LAST:event_outfitNameInputActionPerformed

    private void brandInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandInputActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        String outfitName = outfitNameInput.getText();
        String brandName = brandInput.getText();
        ClothingType clothingType = (ClothingType) clothingTypeList.getSelectedItem();
        Gender genderType = (Gender) genderList.getSelectedItem();
        Size size = (Size) sizeList.getSelectedItem();
        Color color = (Color) colorList.getSelectedItem();

        boolean check= false;
        for(Outfit outfit: Data.outfitsList){
            if(outfit.getName().equals(outfitName)){
                check=true;
                break;
            }
        }
        if(outfitName.equals("") || check || brandName.equals("")){
            JOptionPane.showMessageDialog(this,"Unacceptable name");
        }
        else{
            JOptionPane.showMessageDialog(this,"Successfully added");
            OutfitOperations.createOutfit(Objects.requireNonNull(Helper.findCollection(item)),outfitName,brandName,clothingType,genderType,size,color);

        }
    }//GEN-LAST:event_submitButtonMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_exitMouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandInput;
    private javax.swing.JLabel brandName;
    private javax.swing.JLabel clothingType;
    private JComboBox<ClothingType> clothingTypeList;
    private javax.swing.JLabel color;
    private JComboBox<Color> colorList;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private JComboBox<Gender> genderList;
    private javax.swing.JLabel outfitName;
    private javax.swing.JTextField outfitNameInput;
    private javax.swing.JLabel size;
    private JComboBox<Size> sizeList;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
