/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.profile;

import controller.datarecords.Data;
import controller.helper.CollectionOperation;
import controller.helper.Helper;
import controller.helper.OutfitOperations;
import model.clothes.Collection;
import model.clothes.Outfit;
import model.user.User;

import javax.swing.*;
import java.awt.event.MouseEvent;

/**
 *
 * @author tamer
 */
public class Profile extends javax.swing.JPanel {
    private User user;

    /**
     * Creates new form Profile
     */
    public Profile(User user) {
        this.user=user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCollection = new javax.swing.JButton();
        userInfo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outfitList = new javax.swing.JList<>();
        addCollectionInput = new javax.swing.JTextField();
        choosenCollection = new javax.swing.JComboBox<>();
        addOutfit = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        deleteCollection = new javax.swing.JButton();

        addCollection.setText("add Collection");
        addCollection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCollectionMouseClicked(evt);
            }
        });

        userInfo.setEditable(false);
        userInfo.setText(user.toString());
        userInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoActionPerformed(evt);
            }
        });


        outfitList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Select Collection"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(outfitList);

        addCollectionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCollectionInputActionPerformed(evt);
            }
        });

        choosenCollection.setModel(new javax.swing.DefaultComboBoxModel<>(Helper.getCollectionArray(user)));
        choosenCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String[] outfit = choosenCollectionActionPerformed(evt);
                outfitList.setModel((new javax.swing.AbstractListModel<String>() {
                    String[] strings = outfit;
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                }));
            }
        });

        addOutfit.setText("add Outfit");
        addOutfit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOutfitMouseClicked(evt);
            }
        });

        removeButton.setText("Delete Outfit");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });


        deleteCollection.setText("Delete Collection");
        deleteCollection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCollectionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteCollection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addGap(52, 52, 52)
                        .addComponent(addOutfit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(addCollectionInput, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addCollection))
                                .addComponent(choosenCollection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addComponent(userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(choosenCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCollection)
                    .addComponent(addCollectionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOutfit)
                    .addComponent(removeButton)
                    .addComponent(deleteCollection))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoActionPerformed

    }//GEN-LAST:event_userInfoActionPerformed

    private void addCollectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCollectionMouseClicked
        String name = addCollectionInput.getText();
        boolean check= false;
        for(Collection collection: Data.collectionsList){
            if(collection.getName().equals(name)){
                check=true;
                break;
            }
        }
        if(name.equals("")|| check) {
            JOptionPane.showMessageDialog(this,"Unacceptable name");
        }
        else{
            JOptionPane.showMessageDialog(this,"Successfully added");
            CollectionOperation.createCollection(user,name);
        }
        choosenCollection.setModel(new javax.swing.DefaultComboBoxModel<>(Helper.getCollectionArray(user)));
    }//GEN-LAST:event_addCollectionMouseClicked

    private void addCollectionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCollectionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCollectionInputActionPerformed

    private String[] choosenCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosenCollectionActionPerformed
        String item = (String) choosenCollection.getSelectedItem();
        String[] outfitList = Helper.outfitList(item);
        return outfitList;
    }//GEN-LAST:event_choosenCollectionActionPerformed

    private void addOutfitMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddOutfit addOutfit = new AddOutfit(user, (String) choosenCollection.getSelectedItem());
        addOutfit.setVisible(true);
        outfitList.revalidate();
        outfitList.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        String name = outfitList.getSelectedValue();
        String collectionName = (String) choosenCollection.getSelectedItem();
        Collection collection = Helper.findCollection(collectionName);
        Outfit outfit = Helper.findOutfit(name);
        assert collection != null;
        OutfitOperations.deleteOutfit(outfit,collection);
        JOptionPane.showMessageDialog(this,"Successful");
    }//GEN-LAST:event_removeButtonMouseClicked

    private void deleteCollectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCollectionMouseClicked
        String name = (String) choosenCollection.getSelectedItem();
        Collection collection = Helper.findCollection(name);
        assert collection != null;
        CollectionOperation.deleteCollection(user,collection);
        JOptionPane.showMessageDialog(this,"Successful");
        choosenCollection.setModel(new javax.swing.DefaultComboBoxModel<>(Helper.getCollectionArray(user)));
    }//GEN-LAST:event_deleteCollectionMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCollection;
    private javax.swing.JTextField addCollectionInput;
    private javax.swing.JButton addOutfit;
    private javax.swing.JComboBox<String> choosenCollection;
    private javax.swing.JButton deleteCollection;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> outfitList;
    private javax.swing.JButton removeButton;
    public javax.swing.JTextField userInfo;
    // End of variables declaration//GEN-END:variables
}


